// AUTO-GENERATED by codegen/emit-modules.mjs — do not edit by hand.
// Shared type helpers that map generated OpenAPI `paths` entries to the SDK's
// method param + response types, wrapped in the existing ApiResponse envelope.
import type { paths } from '../schema';
import type { ApiResponse } from '../../types/common';

export type { paths };
export type { ApiResponse };

type Method = 'get' | 'post' | 'put' | 'delete';

// Query params for a given path+verb (undefined -> no params).
export type QueryParams<
  P extends keyof paths,
  V extends Method,
> = paths[P] extends Record<V, { parameters: { query?: infer Q } }>
  ? Q
  : never;

// 200 response body for a given path+verb (unknown when the spec omits it).
export type ResponseOf<
  P extends keyof paths,
  V extends Method,
> = paths[P] extends Record<
  V,
  { responses: { 200: { content: { 'application/json': infer R } } } }
>
  ? R
  : unknown;

// Full method return type: the raw response body wrapped in ApiResponse.
export type Result<P extends keyof paths, V extends Method> = Promise<
  ApiResponse<ResponseOf<P, V>>
>;
