#!/usr/bin/env node
/**
 * codegen/emit-modules.mjs — emit per-module TS classes from the OpenAPI spec.
 *
 * For each operation:
 *   - If (VERB, normalized-path) is in overrides.json -> use the FROZEN method
 *     name + module (guarantees zero public-API break for the existing surface).
 *   - Else -> route by tag (tag-module-map.json) and derive the method name from
 *     the path (deriveName). New endpoints only.
 *
 * Each emitted method is thin:
 *     methodName(params?) { return this.httpClient.get<T>('/path', params); }
 * types come from src/generated/schema.ts (paths[...]). RPC endpoints are skipped
 * (tag-module-map maps them to null, per product decision).
 *
 * Output: src/generated/modules/<module>.ts (one file per module).
 * Run via: pnpm run codegen  (generate.mjs calls this after schema gen)
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SPEC = resolve(ROOT, 'spec/openapi.json');
const OVERRIDES = JSON.parse(readFileSync(resolve(__dirname, 'overrides.json'), 'utf8'));
const TAG_MODULE = JSON.parse(readFileSync(resolve(__dirname, 'tag-module-map.json'), 'utf8'));
const OUT_DIR = resolve(ROOT, 'src/generated/modules');

const VERBS = ['get', 'post', 'put', 'delete'];

/** normalize /a/{id}/b -> /a/{param}/b so keys match overrides.json */
const norm = (p) => p.replace(/\{[^}]+\}/g, '{param}');

/** derive a camelCase method name from a path (new endpoints only). */
function deriveName(verb, path) {
  const parts = path
    .replace(/^\/api\//, '')
    .split('/')
    .filter(Boolean)
    .filter((s) => !/^v\d+$/.test(s)) // drop version segments
    .map((s) => (s.startsWith('{') ? 'By' + cap(s.slice(1, -1)) : s));
  const camel = parts
    .map((s, i) => s.split(/[_-]/).map((w, j) => (i === 0 && j === 0 ? w : cap(w))).join(''))
    .join('');
  const prefix = verb === 'get' ? 'get' : verb; // post/put/delete keep verb as prefix
  return prefix + cap(camel);
}
const cap = (s) => (s ? s[0].toUpperCase() + s.slice(1) : s);

/** collect path params for a method signature */
function pathParams(path) {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
}

function main() {
  const spec = JSON.parse(readFileSync(SPEC, 'utf8'));
  const byModule = {}; // module -> [{method, verb, path, params}]
  const seen = new Set(); // module::method dedupe

  for (const [path, item] of Object.entries(spec.paths)) {
    for (const verb of VERBS) {
      const op = item[verb];
      if (!op) continue;

      const key = `${verb.toUpperCase()} ${norm(path)}`;
      let module, method;

      if (OVERRIDES[key]) {
        ({ module, method } = OVERRIDES[key]);
      } else {
        const tags = op.tags || ['_untagged'];
        module = tags.map((t) => TAG_MODULE[t]).find((m) => m !== undefined);
        if (module === null) continue; // intentionally excluded (rpc)
        if (module === undefined) {
          throw new Error(`No module route for ${key} (tags: ${tags}). Update tag-module-map.json.`);
        }
        method = deriveName(verb, path);
      }

      const dedupeKey = `${module}::${method}`;
      if (seen.has(dedupeKey)) continue;
      seen.add(dedupeKey);

      (byModule[module] ??= []).push({ method, verb, path, params: pathParams(path) });
    }
  }

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  for (const [module, methods] of Object.entries(byModule)) {
    methods.sort((a, b) => a.method.localeCompare(b.method));
    writeFileSync(resolve(OUT_DIR, `${module}.ts`), renderModule(module, methods));
  }

  // index re-exporting every generated module class
  const idx = Object.keys(byModule)
    .sort()
    .map((m) => `export { ${className(m)} } from './${m}';`)
    .join('\n');
  writeFileSync(resolve(OUT_DIR, 'index.ts'), idx + '\n');

  console.log(`✓ emitted ${Object.keys(byModule).length} modules, ${seen.size} methods -> ${OUT_DIR}`);
  for (const [m, ms] of Object.entries(byModule)) console.log(`    ${className(m)}: ${ms.length}`);
}

const className = (m) => cap(m) + 'Module';

function renderModule(module, methods) {
  const lines = [];
  lines.push(`// AUTO-GENERATED by codegen/emit-modules.mjs — do not edit by hand.`);
  lines.push(`// Regenerate with: pnpm run codegen`);
  lines.push(`import type { HttpClient } from '../../client/http-client';`);
  lines.push('');
  lines.push(`export class ${className(module)} {`);
  lines.push(`  constructor(private httpClient: HttpClient) {}`);
  for (const { method, verb, path, params } of methods) {
    const args = [];
    for (const p of params) args.push(`${camelId(p)}: string | number`);
    args.push('params?: Record<string, unknown>');
    const url = params.length
      ? '`' + path.replace(/\{([^}]+)\}/g, (_, p) => '${' + camelId(p) + '}') + '`'
      : `'${path}'`;
    lines.push('');
    lines.push(`  ${method}(${args.join(', ')}) {`);
    lines.push(`    return this.httpClient.${verb}(${url}, params);`);
    lines.push(`  }`);
  }
  lines.push(`}`);
  return lines.join('\n') + '\n';
}

const camelId = (s) => s.split(/[_-]/).map((w, i) => (i === 0 ? w : cap(w))).join('');

main();
