// AUTO-GENERATED contract fixture — the frozen public REST surface (Phase 1).
// Source: parsed from taostat/ts-sdk main @ 2026-07-11 (string + template-literal paths).
// {param} marks a path parameter interpolated at call time.
// Any change to this file is a PUBLIC API CHANGE — review required.

export interface ContractEntry {
  module: string;
  method: string;
  verb: 'get' | 'post' | 'put' | 'delete';
  path: string;
}

export const FROZEN_CONTRACT: ContractEntry[] = [
  {
    module: 'accounts',
    method: 'getAccount',
    verb: 'get',
    path: '/api/account/latest/v1',
  },
  {
    module: 'accounts',
    method: 'getAccountHistory',
    verb: 'get',
    path: '/api/account/history/v1',
  },
  {
    module: 'accounts',
    method: 'getOnChainIdentity',
    verb: 'get',
    path: '/api/identity/latest/v1',
  },
  {
    module: 'accounts',
    method: 'getPendingColdkeySwap',
    verb: 'get',
    path: '/api/pending_coldkey_swap/v1',
  },
  {
    module: 'accounts',
    method: 'getTransfers',
    verb: 'get',
    path: '/api/transfer/v1',
  },
  {
    module: 'chain',
    method: 'getBlockNumbersByInterval',
    verb: 'get',
    path: '/api/block/interval/v1',
  },
  {
    module: 'chain',
    method: 'getBlocks',
    verb: 'get',
    path: '/api/block/v1',
  },
  {
    module: 'chain',
    method: 'getChainCalls',
    verb: 'get',
    path: '/api/call/v1',
  },
  {
    module: 'chain',
    method: 'getEvents',
    verb: 'get',
    path: '/api/event/v1',
  },
  {
    module: 'chain',
    method: 'getExtrinsics',
    verb: 'get',
    path: '/api/extrinsic/v1',
  },
  {
    module: 'chain',
    method: 'getLatestStats',
    verb: 'get',
    path: '/api/stats/latest/v1',
  },
  {
    module: 'chain',
    method: 'getProxyCalls',
    verb: 'get',
    path: '/api/proxy_call/v1',
  },
  {
    module: 'chain',
    method: 'getRuntimeVersion',
    verb: 'get',
    path: '/api/runtime_version/latest/v1',
  },
  {
    module: 'chain',
    method: 'getRuntimeVersionHistory',
    verb: 'get',
    path: '/api/runtime_version/history/v1',
  },
  {
    module: 'chain',
    method: 'getStatsHistory',
    verb: 'get',
    path: '/api/stats/history/v1',
  },
  {
    module: 'delegations',
    method: 'getDelegationEvents',
    verb: 'get',
    path: '/api/delegation/v1',
  },
  {
    module: 'delegations',
    method: 'getSlippage',
    verb: 'get',
    path: '/api/dtao/slippage/v1',
  },
  {
    module: 'delegations',
    method: 'getStakeBalanceSumInTao',
    verb: 'get',
    path: '/api/dtao/stake_balance_aggregated/latest/v1',
  },
  {
    module: 'delegations',
    method: 'getdTaoHistoricalStakeBalance',
    verb: 'get',
    path: '/api/dtao/stake_balance/history/v1',
  },
  {
    module: 'delegations',
    method: 'getdTaoStakeBalance',
    verb: 'get',
    path: '/api/dtao/stake_balance/latest/v1',
  },
  {
    module: 'live',
    method: 'getExtrinsicsForBlockRange',
    verb: 'get',
    path: '/api/v1/live/blocks',
  },
  {
    module: 'live',
    method: 'getExtrinsicsForSpecificBlock',
    verb: 'get',
    path: '/api/v1/live/blocks/{param}',
  },
  {
    module: 'live',
    method: 'getFreeTaoBalance',
    verb: 'get',
    path: '/api/v1/live/accounts/{param}/balance-info',
  },
  {
    module: 'live',
    method: 'getLatestBlockExtrinsics',
    verb: 'get',
    path: '/api/v1/live/blocks/head',
  },
  {
    module: 'live',
    method: 'getNodeTransactionPool',
    verb: 'get',
    path: '/api/v1/live/node/transaction-pool',
  },
  {
    module: 'live',
    method: 'getNodeVersion',
    verb: 'get',
    path: '/api/v1/live/node/version',
  },
  {
    module: 'live',
    method: 'getPalletByConstants',
    verb: 'get',
    path: '/api/v1/live/pallets/{param}/consts',
  },
  {
    module: 'live',
    method: 'getPalletEvents',
    verb: 'get',
    path: '/api/v1/live/pallets/{param}/events',
  },
  {
    module: 'live',
    method: 'getRawExtrinsicsForSpecificBlock',
    verb: 'get',
    path: '/api/v1/live/blocks/{param}/extrinsics-raw',
  },
  {
    module: 'metagraph',
    method: 'getHistory',
    verb: 'get',
    path: '/api/metagraph/history/v1',
  },
  {
    module: 'metagraph',
    method: 'getLatest',
    verb: 'get',
    path: '/api/metagraph/latest/v1',
  },
  {
    module: 'metagraph',
    method: 'getLatestMinerWeight',
    verb: 'get',
    path: '/api/miner/weights/latest/v1',
  },
  {
    module: 'metagraph',
    method: 'getMinerIncentiveDistributionBySubnet',
    verb: 'get',
    path: '/api/subnet/distribution/incentive/v1',
  },
  {
    module: 'metagraph',
    method: 'getMinerWeightHistory',
    verb: 'get',
    path: '/api/miner/weights/history/v1',
  },
  {
    module: 'metagraph',
    method: 'getNeuronDeregistrations',
    verb: 'get',
    path: '/api/subnet/neuron/deregistration/v1',
  },
  {
    module: 'metagraph',
    method: 'getNeuronRegistrations',
    verb: 'get',
    path: '/api/subnet/neuron/registration/v1',
  },
  {
    module: 'metagraph',
    method: 'getRootSubnet',
    verb: 'get',
    path: '/api/metagraph/root/latest/v1',
  },
  {
    module: 'metagraph',
    method: 'getRootSubnetHistory',
    verb: 'get',
    path: '/api/metagraph/root/history/v1',
  },
  {
    module: 'metagraph',
    method: 'getSubnetAxonIpDistribution',
    verb: 'get',
    path: '/api/subnet/distribution/ip/v1',
  },
  {
    module: 'metagraph',
    method: 'getSubnetColdkeyDistribution',
    verb: 'get',
    path: '/api/subnet/distribution/coldkey/v1',
  },
  {
    module: 'subnets',
    method: 'getCurrentSubnetPools',
    verb: 'get',
    path: '/api/dtao/pool/latest/v1',
  },
  {
    module: 'subnets',
    method: 'getCurrentSubnetRegistrationCost',
    verb: 'get',
    path: '/api/subnet/registration_cost/latest/v1',
  },
  {
    module: 'subnets',
    method: 'getHistoricalSubnetPricesSum',
    verb: 'get',
    path: '/api/dtao/pool/total_price/history/v1',
  },
  {
    module: 'subnets',
    method: 'getLatestSubnetPricesSum',
    verb: 'get',
    path: '/api/dtao/pool/total_price/latest/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetEmission',
    verb: 'get',
    path: '/api/dtao/subnet_emission/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetHistory',
    verb: 'get',
    path: '/api/subnet/history/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetIdentity',
    verb: 'get',
    path: '/api/subnet/identity/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetOwner',
    verb: 'get',
    path: '/api/subnet/owner/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetRegistrationCostHistory',
    verb: 'get',
    path: '/api/subnet/registration_cost/history/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetRegistrations',
    verb: 'get',
    path: '/api/subnet/registration/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnets',
    verb: 'get',
    path: '/api/subnet/latest/v1',
  },
  {
    module: 'subnets',
    method: 'getSubnetsPoolsHistory',
    verb: 'get',
    path: '/api/dtao/pool/history/v1',
  },
  {
    module: 'taoPrices',
    method: 'getTaoPrice',
    verb: 'get',
    path: '/api/price/latest/v1',
  },
  {
    module: 'taoPrices',
    method: 'getTaoPriceHistory',
    verb: 'get',
    path: '/api/price/history/v1',
  },
  {
    module: 'taoPrices',
    method: 'getTaoPriceOHLC',
    verb: 'get',
    path: '/api/price/ohlc/v1',
  },
  {
    module: 'tradingView',
    method: 'getTradingViewHistory',
    verb: 'get',
    path: '/api/dtao/tradingview/udf/history',
  },
  {
    module: 'validators',
    method: 'getAlphaSharesHistory',
    verb: 'get',
    path: '/api/dtao/hotkey_alpha_shares/history/v1',
  },
  {
    module: 'validators',
    method: 'getAlphaSharesLatest',
    verb: 'get',
    path: '/api/dtao/hotkey_alpha_shares/latest/v1',
  },
  {
    module: 'validators',
    method: 'getMetricsHistory',
    verb: 'get',
    path: '/api/validator/metrics/history/v1',
  },
  {
    module: 'validators',
    method: 'getMetricsLatest',
    verb: 'get',
    path: '/api/validator/metrics/latest/v1',
  },
  {
    module: 'validators',
    method: 'getParentChildHotkeyRelationsHistory',
    verb: 'get',
    path: '/api/hotkey/family/history/v1',
  },
  {
    module: 'validators',
    method: 'getParentChildHotkeyRelationsLatest',
    verb: 'get',
    path: '/api/hotkey/family/latest/v1',
  },
  {
    module: 'validators',
    method: 'getPerformance',
    verb: 'get',
    path: '/api/validator/performance/v1',
  },
  {
    module: 'validators',
    method: 'getValidatorHistory',
    verb: 'get',
    path: '/api/validator/history/v1',
  },
  {
    module: 'validators',
    method: 'getValidatorLatest',
    verb: 'get',
    path: '/api/validator/latest/v1',
  },
  {
    module: 'validators',
    method: 'getValidatorsInSubnet',
    verb: 'get',
    path: '/api/dtao/validator/available/v1',
  },
  {
    module: 'validators',
    method: 'getWeightCopiers',
    verb: 'get',
    path: '/api/validator/weight_copier/v1',
  },
  {
    module: 'validators',
    method: 'getWeightsHistory',
    verb: 'get',
    path: '/api/validator/weights/history/v2',
  },
  {
    module: 'validators',
    method: 'getWeightsLatest',
    verb: 'get',
    path: '/api/validator/weights/latest/v2',
  },
  {
    module: 'validators',
    method: 'getYield',
    verb: 'get',
    path: '/api/dtao/validator/yield/latest/v1',
  },
  {
    module: 'validators',
    method: 'getdTaoValidatorHistory',
    verb: 'get',
    path: '/api/dtao/validator/history/v1',
  },
  {
    module: 'validators',
    method: 'getdTaoValidatorLatest',
    verb: 'get',
    path: '/api/dtao/validator/latest/v1',
  },
  {
    module: 'validators',
    method: 'getdTaoValidatorPerformanceHistory',
    verb: 'get',
    path: '/api/dtao/validator/performance/history/v1',
  },
  {
    module: 'validators',
    method: 'getdTaoValidatorPerformanceLatest',
    verb: 'get',
    path: '/api/dtao/validator/performance/latest/v1',
  },
];
